credentials:
  # You can obtain monitoring data of multiple tenants by configuring multiple Tenant information.
  tenantId1:
    accessKey: xxxxxxxxxxxx
    accessKeySecret: xxxxxxxxxxxx
    region: cn-hangzhou

Cron:
  # The spec is parsed using the time zone of this Cron instance as the default.
  Spec: 0 */1 * * * *

metrics:
  acs_alb:
    - name: LoadBalancerActiveConnection
      alias: ActiveConn
      desc: 实例活跃连接数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count"
    - name: LoadBalancerNewConnection
      alias: NewConn
      desc: 实例每秒新建连接数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerInBits
      alias: InBandwidth
      desc: 实例每秒入带宽
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "bits/s"
    - name: LoadBalancerOutBits
      alias: OutBandwidth
      desc: 实例每秒出带宽
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "bits/s"
    - name: LoadBalancerRejectedConnection
      alias: DropConn
      desc: 实例每秒丢弃连接数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerQPS
      alias: Qps
      desc: 实例每秒请求数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCode2XX
      alias: Http2xx
      desc: 实例每秒2XX个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCode3XX
      alias: Http3xx
      desc: 实例每秒3XX个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCode4XX
      alias: Http4xx
      desc: 实例每秒4XX个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCode5XX
      alias: Http5xx
      desc: 实例每秒5XX个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCode502
      alias: Http502
      desc: 实例每秒502个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCode503
      alias: Http503
      desc: 实例每秒503个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCode504
      alias: Http504
      desc: 实例每秒504个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCodeUpstream2XX
      alias: HttpUpstream2xx
      desc: 实例后端每秒2xx个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCodeUpstream3XX
      alias: HttpUpstream3xx
      desc: 实例后端每秒3xx个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCodeUpstream4XX
      alias: HttpUpstream4xx
      desc: 实例后端每秒4xx个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerHTTPCodeUpstream5XX
      alias: HttpUpstream5xx
      desc: 实例后端每秒5XX个数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count/s"
    - name: LoadBalancerUnHealthyHostCount
      alias: UnhealthyServers
      desc: 实例异常主机数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count"
    - name: LoadBalancerHealthyHostCount
      alias: HealthyServers
      desc: 实例健康主机数
      dimensions:
        - loadBalancerId
      measure: Value
      period: 60
      unit: "Count"


  acs_nlb:
    - name: InstanceActiveConnection
      alias: ActiveConn
      desc: 实例活跃连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count"
    - name: InstanceNewConnection
      alias: NewConn
      desc: 实例每秒新建连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceMaxConnection
      alias: ConcurConn
      desc: 实例每秒最大并发连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceInactiveConnection
      alias: InactiveConn
      desc: 实例每秒非活跃连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstancePacketRX
      alias: InPacket
      desc: 实例每秒入包数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstancePacketTX
      alias: OutPacket
      desc: 实例每秒出包数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceTrafficRX
      alias: InBandwidth
      desc: 实例每秒入带宽
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "bits/s"
    - name: InstanceTrafficTX
      alias: OutBandwidth
      desc: 实例每秒出带宽
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "bits/s"
    - name: InstanceDropConnection
      alias: DropConn
      desc: 实例每秒丢弃连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceDropPacketRX
      alias: InDropPacket
      desc: 实例每秒丢弃入包数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceDropPacketTX
      alias: OutDropPacket
      desc: 实例每秒丢弃出包数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceUnhealthyServerCount
      alias: UnhealthyServers
      desc: 实例异常主机数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count"


  acs_slb_dashboard:
    - name: InstanceActiveConnection
      alias: ActiveConn
      desc: 实例活跃连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceNewConnection
      alias: NewConn
      desc: 实例每秒新建连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceMaxConnection
      alias: ConcurConn
      desc: 实例每秒最大并发连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceInactiveConnection
      alias: InactiveConn
      desc: 实例每秒非活跃连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceMaxConnectionUtilization
      alias: ConcurConnUsage
      desc: 实例并发连接数使用率
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "%"
    - name: InstanceNewConnectionUtilization
      alias: NewConnUsage
      desc: 实例新建连接数使用率
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "%"
    - name: InstancePacketRX
      alias: InPacket
      desc: 实例每秒入包数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstancePacketTX
      alias: OutPacket
      desc: 实例每秒出包数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceTrafficRX
      alias: InTraffic
      desc: 实例每秒入流量
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "bits/s"
    - name: InstanceTrafficTX
      alias: OutTraffic
      desc: 实例每秒出流量
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "bits/s"
    - name: InstanceDropConnection
      alias: DropConn
      desc: 实例每秒丢弃连接数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceDropPacketRX
      alias: InDropPacket
      desc: 实例每秒丢弃入包数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceDropPacketTX
      alias: OutDropPacket
      desc: 实例每秒丢弃出包数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: Rt
      desc: 实例平均响应时间
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceQps
      alias: Qps
      desc: 实例每秒请求数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceQpsUtilization
      alias: QpsUsage
      desc: 实例QPS使用率
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "%"
    - name: InstanceStatusCode2xx
      alias: Http2xx
      desc: 实例每秒2XX个数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceStatusCode3xx
      alias: Http3xx
      desc: 实例每秒3XX个数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceStatusCode4xx
      alias: Http4xx
      desc: 实例每秒4XX个数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceStatusCode5xx
      alias: Http5xx
      desc: 实例每秒5XX个数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceUpstreamCode4xx
      alias: HttpUpstream4xx
      desc: 实例后端每秒4XX个数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: InstanceUpstreamCode5xx
      alias: HttpUpstream5xx
      desc: 实例后端每秒5XX个数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count/s"
    - name: UnhealthyServerCount
      alias: UnhealthyServers
      desc: 实例异常主机数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count"
    - name: HeathyServerCount
      alias: HealthyServers
      desc: 实例健康主机数
      dimensions:
        - instanceId
      measure: Average
      period: 60
      unit: "Count"
